service: authorization-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    excludeFiles: src/**/*.test.js
  stage: dev

resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt: [BasicAuthorizerLambdaFunction, Arn]

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
              
